// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'api.freezed.dart';

@freezed
sealed class AppEvent with _$AppEvent {
  const AppEvent._();

  const factory AppEvent.configChanged() = AppEvent_ConfigChanged;
  const factory AppEvent.accountsChanged() = AppEvent_AccountsChanged;
  const factory AppEvent.instancesChanged() = AppEvent_InstancesChanged;
  const factory AppEvent.taskChanged(String field0) = AppEvent_TaskChanged;
  const factory AppEvent.javaRuntimesChanged() = AppEvent_JavaRuntimesChanged;
  const factory AppEvent.versionListChanged() = AppEvent_VersionListChanged;
}

@freezed
sealed class GameState with _$GameState {
  const GameState._();

  const factory GameState.starting() = GameState_Starting;
  const factory GameState.running() = GameState_Running;
  const factory GameState.stopped(int field0) = GameState_Stopped;
  const factory GameState.crashed(String field0) = GameState_Crashed;
}

@freezed
sealed class JavaSelection with _$JavaSelection {
  const JavaSelection._();

  const factory JavaSelection.auto(int field0) = JavaSelection_Auto;
  const factory JavaSelection.manual(String field0) = JavaSelection_Manual;
}

@freezed
sealed class Source with _$Source {
  const Source._();

  const factory Source.official() = Source_Official;
  const factory Source.bmclapi() = Source_Bmclapi;
  const factory Source.custom(String field0) = Source_Custom;
}

@freezed
sealed class YuhinaErrorKind with _$YuhinaErrorKind {
  const YuhinaErrorKind._();

  const factory YuhinaErrorKind.network() = YuhinaErrorKind_Network;
  const factory YuhinaErrorKind.http(int field0, String field1) =
      YuhinaErrorKind_Http;
  const factory YuhinaErrorKind.auth() = YuhinaErrorKind_Auth;
  const factory YuhinaErrorKind.authExpired() = YuhinaErrorKind_AuthExpired;
  const factory YuhinaErrorKind.notLoggedIn() = YuhinaErrorKind_NotLoggedIn;
  const factory YuhinaErrorKind.versionNotFound() =
      YuhinaErrorKind_VersionNotFound;
  const factory YuhinaErrorKind.loaderNotInstalled() =
      YuhinaErrorKind_LoaderNotInstalled;
  const factory YuhinaErrorKind.javaNotFound() = YuhinaErrorKind_JavaNotFound;
  const factory YuhinaErrorKind.invalidInstance() =
      YuhinaErrorKind_InvalidInstance;
  const factory YuhinaErrorKind.modConflict() = YuhinaErrorKind_ModConflict;
  const factory YuhinaErrorKind.modpackInvalid() =
      YuhinaErrorKind_ModpackInvalid;
  const factory YuhinaErrorKind.checksumMismatch() =
      YuhinaErrorKind_ChecksumMismatch;
  const factory YuhinaErrorKind.downloadFailed() =
      YuhinaErrorKind_DownloadFailed;
  const factory YuhinaErrorKind.canceled() = YuhinaErrorKind_Canceled;
  const factory YuhinaErrorKind.io() = YuhinaErrorKind_Io;
  const factory YuhinaErrorKind.internal() = YuhinaErrorKind_Internal;
}
