// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'service.dart';
import 'third_party/yuhina_api/error.dart';
import 'third_party/yuhina_api/types.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_YuhinaServicePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaServicePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  YuhinaService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    dynamic raw,
  );

  @protected
  YuhinaService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    dynamic raw,
  );

  @protected
  YuhinaService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    dynamic raw,
  );

  @protected
  RustStreamSink<AppEvent> dco_decode_StreamSink_app_event_Sse(dynamic raw);

  @protected
  RustStreamSink<DownloadProgressEvent>
  dco_decode_StreamSink_download_progress_event_Sse(dynamic raw);

  @protected
  RustStreamSink<GameOutput> dco_decode_StreamSink_game_output_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  Account dco_decode_account(dynamic raw);

  @protected
  AccountKind dco_decode_account_kind(dynamic raw);

  @protected
  AppEvent dco_decode_app_event(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  Account dco_decode_box_autoadd_account(dynamic raw);

  @protected
  AccountKind dco_decode_box_autoadd_account_kind(dynamic raw);

  @protected
  CreateInstanceRequest dco_decode_box_autoadd_create_instance_request(
    dynamic raw,
  );

  @protected
  LaunchArgs dco_decode_box_autoadd_launch_args(dynamic raw);

  @protected
  LauncherConfig dco_decode_box_autoadd_launcher_config(dynamic raw);

  @protected
  Loader dco_decode_box_autoadd_loader(dynamic raw);

  @protected
  MicrosoftLoginHandle dco_decode_box_autoadd_microsoft_login_handle(
    dynamic raw,
  );

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ConflictKind dco_decode_conflict_kind(dynamic raw);

  @protected
  ConflictSeverity dco_decode_conflict_severity(dynamic raw);

  @protected
  CreateInstanceRequest dco_decode_create_instance_request(dynamic raw);

  @protected
  DownloadProgressEvent dco_decode_download_progress_event(dynamic raw);

  @protected
  DownloadState dco_decode_download_state(dynamic raw);

  @protected
  DownloadTask dco_decode_download_task(dynamic raw);

  @protected
  GameLogEntry dco_decode_game_log_entry(dynamic raw);

  @protected
  GameOutput dco_decode_game_output(dynamic raw);

  @protected
  GameSession dco_decode_game_session(dynamic raw);

  @protected
  GameState dco_decode_game_state(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  InstalledMod dco_decode_installed_mod(dynamic raw);

  @protected
  InstanceDetail dco_decode_instance_detail(dynamic raw);

  @protected
  InstanceSummary dco_decode_instance_summary(dynamic raw);

  @protected
  JavaRuntime dco_decode_java_runtime(dynamic raw);

  @protected
  JavaSelection dco_decode_java_selection(dynamic raw);

  @protected
  JavaSource dco_decode_java_source(dynamic raw);

  @protected
  LaunchArgs dco_decode_launch_args(dynamic raw);

  @protected
  LauncherConfig dco_decode_launcher_config(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<Account> dco_decode_list_account(dynamic raw);

  @protected
  List<DownloadTask> dco_decode_list_download_task(dynamic raw);

  @protected
  List<GameLogEntry> dco_decode_list_game_log_entry(dynamic raw);

  @protected
  List<GameSession> dco_decode_list_game_session(dynamic raw);

  @protected
  List<InstalledMod> dco_decode_list_installed_mod(dynamic raw);

  @protected
  List<InstanceSummary> dco_decode_list_instance_summary(dynamic raw);

  @protected
  List<JavaRuntime> dco_decode_list_java_runtime(dynamic raw);

  @protected
  List<ModConflict> dco_decode_list_mod_conflict(dynamic raw);

  @protected
  List<ModUpdate> dco_decode_list_mod_update(dynamic raw);

  @protected
  List<ModrinthDependency> dco_decode_list_modrinth_dependency(dynamic raw);

  @protected
  List<ModrinthFile> dco_decode_list_modrinth_file(dynamic raw);

  @protected
  List<ModrinthProject> dco_decode_list_modrinth_project(dynamic raw);

  @protected
  List<ModrinthVersion> dco_decode_list_modrinth_version(dynamic raw);

  @protected
  List<NewsItem> dco_decode_list_news_item(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<VersionMeta> dco_decode_list_version_meta(dynamic raw);

  @protected
  Loader dco_decode_loader(dynamic raw);

  @protected
  LoaderKind dco_decode_loader_kind(dynamic raw);

  @protected
  LogLevel dco_decode_log_level(dynamic raw);

  @protected
  MicrosoftLoginHandle dco_decode_microsoft_login_handle(dynamic raw);

  @protected
  ModConflict dco_decode_mod_conflict(dynamic raw);

  @protected
  ModUpdate dco_decode_mod_update(dynamic raw);

  @protected
  ModrinthDependency dco_decode_modrinth_dependency(dynamic raw);

  @protected
  ModrinthFile dco_decode_modrinth_file(dynamic raw);

  @protected
  ModrinthProject dco_decode_modrinth_project(dynamic raw);

  @protected
  ModrinthVersion dco_decode_modrinth_version(dynamic raw);

  @protected
  NewsItem dco_decode_news_item(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Account? dco_decode_opt_box_autoadd_account(dynamic raw);

  @protected
  AccountKind? dco_decode_opt_box_autoadd_account_kind(dynamic raw);

  @protected
  LaunchArgs? dco_decode_opt_box_autoadd_launch_args(dynamic raw);

  @protected
  Loader? dco_decode_opt_box_autoadd_loader(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  SearchResult dco_decode_search_result(dynamic raw);

  @protected
  Source dco_decode_source(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VersionMeta dco_decode_version_meta(dynamic raw);

  @protected
  YuhinaError dco_decode_yuhina_error(dynamic raw);

  @protected
  YuhinaErrorKind dco_decode_yuhina_error_kind(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  YuhinaService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    SseDeserializer deserializer,
  );

  @protected
  YuhinaService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    SseDeserializer deserializer,
  );

  @protected
  YuhinaService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<AppEvent> sse_decode_StreamSink_app_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<DownloadProgressEvent>
  sse_decode_StreamSink_download_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<GameOutput> sse_decode_StreamSink_game_output_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  Account sse_decode_account(SseDeserializer deserializer);

  @protected
  AccountKind sse_decode_account_kind(SseDeserializer deserializer);

  @protected
  AppEvent sse_decode_app_event(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  Account sse_decode_box_autoadd_account(SseDeserializer deserializer);

  @protected
  AccountKind sse_decode_box_autoadd_account_kind(SseDeserializer deserializer);

  @protected
  CreateInstanceRequest sse_decode_box_autoadd_create_instance_request(
    SseDeserializer deserializer,
  );

  @protected
  LaunchArgs sse_decode_box_autoadd_launch_args(SseDeserializer deserializer);

  @protected
  LauncherConfig sse_decode_box_autoadd_launcher_config(
    SseDeserializer deserializer,
  );

  @protected
  Loader sse_decode_box_autoadd_loader(SseDeserializer deserializer);

  @protected
  MicrosoftLoginHandle sse_decode_box_autoadd_microsoft_login_handle(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ConflictKind sse_decode_conflict_kind(SseDeserializer deserializer);

  @protected
  ConflictSeverity sse_decode_conflict_severity(SseDeserializer deserializer);

  @protected
  CreateInstanceRequest sse_decode_create_instance_request(
    SseDeserializer deserializer,
  );

  @protected
  DownloadProgressEvent sse_decode_download_progress_event(
    SseDeserializer deserializer,
  );

  @protected
  DownloadState sse_decode_download_state(SseDeserializer deserializer);

  @protected
  DownloadTask sse_decode_download_task(SseDeserializer deserializer);

  @protected
  GameLogEntry sse_decode_game_log_entry(SseDeserializer deserializer);

  @protected
  GameOutput sse_decode_game_output(SseDeserializer deserializer);

  @protected
  GameSession sse_decode_game_session(SseDeserializer deserializer);

  @protected
  GameState sse_decode_game_state(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  InstalledMod sse_decode_installed_mod(SseDeserializer deserializer);

  @protected
  InstanceDetail sse_decode_instance_detail(SseDeserializer deserializer);

  @protected
  InstanceSummary sse_decode_instance_summary(SseDeserializer deserializer);

  @protected
  JavaRuntime sse_decode_java_runtime(SseDeserializer deserializer);

  @protected
  JavaSelection sse_decode_java_selection(SseDeserializer deserializer);

  @protected
  JavaSource sse_decode_java_source(SseDeserializer deserializer);

  @protected
  LaunchArgs sse_decode_launch_args(SseDeserializer deserializer);

  @protected
  LauncherConfig sse_decode_launcher_config(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<Account> sse_decode_list_account(SseDeserializer deserializer);

  @protected
  List<DownloadTask> sse_decode_list_download_task(
    SseDeserializer deserializer,
  );

  @protected
  List<GameLogEntry> sse_decode_list_game_log_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<GameSession> sse_decode_list_game_session(SseDeserializer deserializer);

  @protected
  List<InstalledMod> sse_decode_list_installed_mod(
    SseDeserializer deserializer,
  );

  @protected
  List<InstanceSummary> sse_decode_list_instance_summary(
    SseDeserializer deserializer,
  );

  @protected
  List<JavaRuntime> sse_decode_list_java_runtime(SseDeserializer deserializer);

  @protected
  List<ModConflict> sse_decode_list_mod_conflict(SseDeserializer deserializer);

  @protected
  List<ModUpdate> sse_decode_list_mod_update(SseDeserializer deserializer);

  @protected
  List<ModrinthDependency> sse_decode_list_modrinth_dependency(
    SseDeserializer deserializer,
  );

  @protected
  List<ModrinthFile> sse_decode_list_modrinth_file(
    SseDeserializer deserializer,
  );

  @protected
  List<ModrinthProject> sse_decode_list_modrinth_project(
    SseDeserializer deserializer,
  );

  @protected
  List<ModrinthVersion> sse_decode_list_modrinth_version(
    SseDeserializer deserializer,
  );

  @protected
  List<NewsItem> sse_decode_list_news_item(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<VersionMeta> sse_decode_list_version_meta(SseDeserializer deserializer);

  @protected
  Loader sse_decode_loader(SseDeserializer deserializer);

  @protected
  LoaderKind sse_decode_loader_kind(SseDeserializer deserializer);

  @protected
  LogLevel sse_decode_log_level(SseDeserializer deserializer);

  @protected
  MicrosoftLoginHandle sse_decode_microsoft_login_handle(
    SseDeserializer deserializer,
  );

  @protected
  ModConflict sse_decode_mod_conflict(SseDeserializer deserializer);

  @protected
  ModUpdate sse_decode_mod_update(SseDeserializer deserializer);

  @protected
  ModrinthDependency sse_decode_modrinth_dependency(
    SseDeserializer deserializer,
  );

  @protected
  ModrinthFile sse_decode_modrinth_file(SseDeserializer deserializer);

  @protected
  ModrinthProject sse_decode_modrinth_project(SseDeserializer deserializer);

  @protected
  ModrinthVersion sse_decode_modrinth_version(SseDeserializer deserializer);

  @protected
  NewsItem sse_decode_news_item(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Account? sse_decode_opt_box_autoadd_account(SseDeserializer deserializer);

  @protected
  AccountKind? sse_decode_opt_box_autoadd_account_kind(
    SseDeserializer deserializer,
  );

  @protected
  LaunchArgs? sse_decode_opt_box_autoadd_launch_args(
    SseDeserializer deserializer,
  );

  @protected
  Loader? sse_decode_opt_box_autoadd_loader(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
    SseDeserializer deserializer,
  );

  @protected
  SearchResult sse_decode_search_result(SseDeserializer deserializer);

  @protected
  Source sse_decode_source(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VersionMeta sse_decode_version_meta(SseDeserializer deserializer);

  @protected
  YuhinaError sse_decode_yuhina_error(SseDeserializer deserializer);

  @protected
  YuhinaErrorKind sse_decode_yuhina_error_kind(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    YuhinaService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    YuhinaService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    YuhinaService self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_app_event_Sse(
    RustStreamSink<AppEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_download_progress_event_Sse(
    RustStreamSink<DownloadProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_game_output_Sse(
    RustStreamSink<GameOutput> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_account_kind(AccountKind self, SseSerializer serializer);

  @protected
  void sse_encode_app_event(AppEvent self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account(Account self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_account_kind(
    AccountKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_create_instance_request(
    CreateInstanceRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_launch_args(
    LaunchArgs self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_launcher_config(
    LauncherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_loader(Loader self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_microsoft_login_handle(
    MicrosoftLoginHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_kind(ConflictKind self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_severity(
    ConflictSeverity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_create_instance_request(
    CreateInstanceRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_progress_event(
    DownloadProgressEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_download_state(DownloadState self, SseSerializer serializer);

  @protected
  void sse_encode_download_task(DownloadTask self, SseSerializer serializer);

  @protected
  void sse_encode_game_log_entry(GameLogEntry self, SseSerializer serializer);

  @protected
  void sse_encode_game_output(GameOutput self, SseSerializer serializer);

  @protected
  void sse_encode_game_session(GameSession self, SseSerializer serializer);

  @protected
  void sse_encode_game_state(GameState self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_installed_mod(InstalledMod self, SseSerializer serializer);

  @protected
  void sse_encode_instance_detail(
    InstanceDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_instance_summary(
    InstanceSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_java_runtime(JavaRuntime self, SseSerializer serializer);

  @protected
  void sse_encode_java_selection(JavaSelection self, SseSerializer serializer);

  @protected
  void sse_encode_java_source(JavaSource self, SseSerializer serializer);

  @protected
  void sse_encode_launch_args(LaunchArgs self, SseSerializer serializer);

  @protected
  void sse_encode_launcher_config(
    LauncherConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_account(List<Account> self, SseSerializer serializer);

  @protected
  void sse_encode_list_download_task(
    List<DownloadTask> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_log_entry(
    List<GameLogEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_game_session(
    List<GameSession> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_installed_mod(
    List<InstalledMod> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_instance_summary(
    List<InstanceSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_java_runtime(
    List<JavaRuntime> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mod_conflict(
    List<ModConflict> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_mod_update(
    List<ModUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_modrinth_dependency(
    List<ModrinthDependency> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_modrinth_file(
    List<ModrinthFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_modrinth_project(
    List<ModrinthProject> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_modrinth_version(
    List<ModrinthVersion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_news_item(List<NewsItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_version_meta(
    List<VersionMeta> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_loader(Loader self, SseSerializer serializer);

  @protected
  void sse_encode_loader_kind(LoaderKind self, SseSerializer serializer);

  @protected
  void sse_encode_log_level(LogLevel self, SseSerializer serializer);

  @protected
  void sse_encode_microsoft_login_handle(
    MicrosoftLoginHandle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_mod_conflict(ModConflict self, SseSerializer serializer);

  @protected
  void sse_encode_mod_update(ModUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_modrinth_dependency(
    ModrinthDependency self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_modrinth_file(ModrinthFile self, SseSerializer serializer);

  @protected
  void sse_encode_modrinth_project(
    ModrinthProject self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_modrinth_version(
    ModrinthVersion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_news_item(NewsItem self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_account(
    Account? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_account_kind(
    AccountKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_launch_args(
    LaunchArgs? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_loader(
    Loader? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
    (String, String) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_search_result(SearchResult self, SseSerializer serializer);

  @protected
  void sse_encode_source(Source self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_version_meta(VersionMeta self, SseSerializer serializer);

  @protected
  void sse_encode_yuhina_error(YuhinaError self, SseSerializer serializer);

  @protected
  void sse_encode_yuhina_error_kind(
    YuhinaErrorKind self,
    SseSerializer serializer,
  );
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaServicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_yuhina_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaServicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaServicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_yuhina_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaService =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerYuhinaServicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
