// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'third_party/yuhina_api/error.dart';
import 'third_party/yuhina_api/types.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YuhinaService>>
abstract class YuhinaService implements RustOpaqueInterface {
  Future<JavaRuntime> addManualJava({required String path});

  Future<Account> addOfflineAccount({required String username});

  Future<Account> addYggdrasilAccount({
    required String serverUrl,
    required String username,
    required String password,
  });

  Future<MicrosoftLoginHandle> beginMicrosoftLogin();

  Future<void> cancelMicrosoftLogin({required MicrosoftLoginHandle handle});

  Future<void> cancelTask({required String id});

  /// Latest launcher version tag, or `None` when up to date / unavailable.
  Future<String?> checkLauncherUpdate();

  Future<List<ModConflict>> checkModConflicts({required String instanceId});

  Future<List<ModUpdate>> checkModUpdates({required String instanceId});

  Future<void> clearFinishedTasks();

  Future<InstanceSummary> cloneInstance({
    required String id,
    required String newName,
  });

  Future<InstanceSummary> createInstance({required CreateInstanceRequest req});

  Future<void> deleteInstance({required String id, required bool deleteFiles});

  Future<void> deleteMod({required String instanceId, required String modId});

  Future<InstanceSummary> downloadModpackFromModrinth({
    required String projectId,
    required String versionId,
  });

  Future<String> exportModpack({
    required String instanceId,
    required String destPath,
  });

  Future<List<NewsItem>> fetchNews();

  Future<List<VersionMeta>> fetchVersionList();

  /// Fails with `Auth(NotLoggedIn)` when no active account exists.
  Future<Account> getActiveAccount();

  Future<LauncherConfig> getConfig();

  Future<List<GameLogEntry>> getGameLogs({
    required String sessionId,
    required BigInt afterIndex,
  });

  Future<GameSession> getGameSession({required String sessionId});

  Future<InstanceDetail> getInstance({required String id});

  Future<ModrinthProject> getModProject({required String projectId});

  Future<List<NewsItem>> getNews();

  Future<List<VersionMeta>> getVersionList();

  Future<InstanceSummary> importModpack({
    required String mrpackPath,
    required String name,
  });

  Future<void> installInstanceLoader({
    required String id,
    required Loader loader,
  });

  /// Progress is surfaced through `watch_progress` (the core enqueues a task).
  Future<JavaRuntime> installJava({required int major});

  /// `version_id: None` auto-selects the latest compatible version.
  Future<InstalledMod> installMod({
    required String instanceId,
    required String projectId,
    String? versionId,
  });

  Future<InstalledMod> installModFile({
    required String instanceId,
    required String path,
  });

  Future<GameSession> launchInstance({required String instanceId});

  Future<List<Account>> listAccounts();

  Future<List<DownloadTask>> listDownloadTasks();

  Future<List<GameSession>> listGameSessions();

  Future<List<InstanceSummary>> listInstances();

  Future<List<JavaRuntime>> listJavaRuntimes();

  Future<List<ModrinthVersion>> listModVersions({
    required String projectId,
    required List<String> loaders,
    required List<String> gameVersions,
  });

  Future<List<InstalledMod>> listMods({required String instanceId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// Construct every domain service over `<data_dir>/yuhina.db` and wire the
  /// global event bus. Call once at app startup.
  static Future<YuhinaService> newInstance({required LauncherConfig config}) =>
      RustLib.instance.api.crateServiceYuhinaServiceNew(config: config);

  Future<void> openGameDir({required String instanceId});

  Future<void> pauseTask({required String id});

  Future<Account?> pollMicrosoftLogin({required MicrosoftLoginHandle handle});

  Future<Account> refreshAccount({required String id});

  Future<void> removeAccount({required String id});

  Future<void> removeJava({required String id});

  Future<void> renameInstance({required String id, required String name});

  /// Resolved absolute data / game-root directories.
  Future<(String, String)> resolveDataPaths();

  Future<void> resumeTask({required String id});

  Future<void> scanSystemJava();

  Future<SearchResult> searchMods({
    required String query,
    required List<String> loaders,
    required List<String> gameVersions,
    required int index,
    required int limit,
  });

  Future<void> setActiveAccount({required String id});

  /// Persist the config; swaps the core downloader for the new mirror source
  /// and emits `ConfigChanged` on the global event stream.
  Future<void> setConfig({required LauncherConfig config});

  Future<void> setInstanceIcon({required String id, required String icon});

  Future<void> setModEnabled({
    required String instanceId,
    required String modId,
    required bool enabled,
  });

  Future<void> stopGame({required String sessionId});

  Future<InstalledMod> updateMod({
    required String instanceId,
    required String modId,
    required String toVersionId,
  });

  /// Global event stream (Config/Accounts/Instances/Tasks/Java/Versions changed).
  Stream<AppEvent> watchEvents();

  /// Real-time stdout/stderr stream for one session (line-delimited).
  Stream<GameOutput> watchGameOutput({required String sessionId});

  /// Global download progress stream (throttled to 100ms by the manager).
  Stream<DownloadProgressEvent> watchProgress();
}
