[package]
name = "yuhina-core"
version.workspace = true
edition.workspace = true

[dependencies]
yuhina-api = { path = "../yuhina-api" }
yuhina-db = { path = "../yuhina-db" }
yuhina-download = { path = "../yuhina-download" }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
sha1 = { workspace = true }
tracing = { workspace = true }
hex = "0.4"
tar = "0.4"
flate2 = "1"
uuid = "1"
libc = "0.2"
async-trait = "0.1"
zip = { version = "2", default-features = false, features = ["deflate"] }

[dev-dependencies]
tempfile = "3"
