[package]
name = "yuhina-integration-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
yuhina-api = { path = "../crates/yuhina-api" }
yuhina-db = { path = "../crates/yuhina-db" }
yuhina-auth = { path = "../crates/yuhina-auth" }
yuhina-download = { path = "../crates/yuhina-download" }
tokio = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true }
base64 = { workspace = true }
yuhina-instance = { version = "0.1.0", path = "../crates/yuhina-instance" }
yuhina-core = { version = "0.1.0", path = "../crates/yuhina-core" }
async-trait = "0.1.92"
zip.workspace = true

[dev-dependencies]
tiny_http = { workspace = true }
tempfile = "3"
uuid = { version = "1", features = ["v4"] }
sha1 = { workspace = true }
axum = "0.7"
